# Generated by Django 3.0.4 on 2020-03-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_of_food',
            field=models.CharField(choices=[('1', 'Salads'), ('2', 'Sandwiches'), ('3', 'Soups'), ('4', 'Main Dishes'), ('5', 'Desserts'), ('6', 'Drinks')], max_length=300, verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/res_app/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
