# Generated by Django 3.0.4 on 2020-03-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_app', '0002_auto_20200318_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/res_app/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
